---
- name: Install Repoo
  tsks:
    - name: Hashicorp
      ansible.builtin.shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      become: true

- name: Install Repoo
  tsks:
    - name: Hashicorp
      ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      become: true

- name: Install Repoo
  tsks:
    - name: Docker
      ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
      become: true

- name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600


- hosts: controlmachine
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
         - ca-certificates
         - gnupg
         - lsb-release
         - jq
         - wget
         - curl
         - unzip
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
         - terraform
