---

- hosts: controlmachine

  tasks:

    - name: install packages

      become: true

      become_user: root

      apt:

        state: present

        name:

         - ca-certificates
         - gnupg
         - lsb-release
         - jq
         - wget
         - curl
         - unzip
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
         - terraform