---

- hosts: controlmachine
  remote_user: root
  tasks:
    - name: Install Repoo
      command:
        #wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

    - name: install packages
      ansible.builtin.apt:
        name:
        - ca-certificates
        - gnupg
        - lsb-release
        - jq
        - wget
        - curl
        - unzip
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - terraform
        update_cache: yes
        state: latest
        install_recommends: yes

    - name: run terraform
      terraform:
        project_path: '/root/tmp/Lab/files'
        state: present
