---

- hosts: controlmachine
  remote_user: root
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name:
        - ca-certificates
        - gnupg
        - lsb-release
        - jq
        - wget
        - curl
        - unzip
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - terraform
        update_cache: yes
        state: latest
        install_recommends: yes


- terraform:
    project_path: 'files/'
    state: present
    force_init: true
