---

- hosts: controlmachine
  remote_user: root
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name:
        - ca-certificates
        - gnupg
        - lsb-release
        - jq
        - wget
        - curl
        - unzip
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - terraform
        update_cache: yes
        state: latest
        install_recommends: yes

- name: terraform
   hosts: controlmachine
   become: true
   become_method: sudo
   become_user: root
   tasks:
      - name: Basic deploy of a service
        community.general.terraform:
        project_path: './'
        state: present